# baseURL
@baseURL = http://localhost:3000

###
# Find All banners
GET {{ baseURL }}/banners

###
# Find banner By Id
GET {{ baseURL }}/banners/1

###
# Create banner
POST {{ baseURL }}/banners
Content-Type: application/json

{
 "name": "广告",
 "links": {
  "baidu": "http://www.baidu.com",
  "google": "http://www.google.com"
 }
}

###
# add img to banner
PUT {{ baseURL }}/banners/1/add/img
Content-Type: application/json

{
 "imgs": [4, 5]
}


###
# add img to banner
PUT {{ baseURL }}/banners/1/remove/img
Content-Type: application/json

{
 "imgs": [4]
}

###
# Delete banner By Id
DELETE {{ baseURL }}/banners/1
