# baseURL
@baseURL = http://localhost:3000

###
# Find All buckets
GET {{ baseURL }}/buckets

###
# Find All buckets
GET {{ baseURL }}/buckets/default

###
# Find food By Id
GET {{ baseURL }}/buckets/1

###
# Create bucket
POST {{ baseURL }}/bucket
Content-Type: application/json

{
 "name": "test"
}

###
#  set default bucket
PUT {{ baseURL }}/buckets/test/default

###
# Delete food By Id
DELETE {{ baseURL }}/buckets/xiaoguan
