# baseURL
@baseURL = http://localhost:3000

###
# Find All buckets
GET {{ baseURL }}/buckets

###
# Find food By Id
GET {{ baseURL }}/foods/1

###
# Create bucket
POST {{ baseURL }}/buckets
Content-Type: application/json

{
 "name": "test"
}

###
# Delete food By Id
DELETE {{ baseURL }}/buckets/test
