# baseURL
@baseURL = http://localhost:3000

@authorization = bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjYwNTU2MTc5LCJleHAiOjE2NjExNjA5Nzl9.9UUOmPOB8mYdwWmnJ2nghLCVd-ojnup-8iugyUq4MEA

###
# find user cart
GET {{ baseURL }}/user/2/cart


###
# clear cart
PUT {{ baseURL }}/user/2/cart/clear


###
# add item to cart
PUT {{ baseURL }}/user/2/cart/add 
Content-Type: application/json

{
  "price": 14.0,
  "qty": 2,
  "specId": 1,
  "totalPrice": 14.0
}

###
# update item qty
PUT {{ baseURL }}/user/2/cart/item/qty
Content-Type: application/json

{
  "id": 51,
  "qty": 3
}





###
# Delete cartItems
DELETE {{ baseURL }}/user/2/cart/remove
Content-Type: application/json

{
  "ids": [41, 40]
}
