# baseURL
@baseURL = http://localhost:3000

###
# Find All files
GET {{ baseURL }}/files

###
# Find food By Id
GET {{ baseURL }}/foods/1

###
# Create file
POST {{ baseURL }}/files
Content-Type: application/json

[
  {
  "filename": "zzzz.png",
  "originName": "yyzc",
  "url": "/xiaoguan/zzzz.png",
  "fileType": "IMAGE",
  "bucketId": 2
}
]


###
# Delete files
DELETE {{ baseURL }}/files
Content-Type: application/json

{
  "bucketName": "xiaoguan",
  "fileIds": [1,2]
}
