# baseURL
@baseURL = http://localhost:3000

###
# Find All files
GET {{ baseURL }}/files/test

###
# Find file By Id
GET {{ baseURL }}/files/1

###
# upload a file from url
POST {{ baseURL }}/files/upload/test/remote
Content-Type: application/json

{
  "url": "https://lmg.jj20.com/up/allimg/1113/092219135626/1Z922135626-3-1200.jpg"
}


###
# Update file Optional field
PUT {{ baseURL }}/files/3
Content-Type: application/json

{
  "title": "金典菜式",
  "link": "https://baidu.com"
}


###
# Delete files
DELETE {{ baseURL }}/files/test
Content-Type: application/json

{
  "filenames": ["Nf1E56f.webp"]
}
