# baseURL
@baseURL = http://localhost:3000

###
# Find All files
GET {{ baseURL }}/files/test

###
# Find food By Id
GET {{ baseURL }}/foods/1


###
# Update file Optional field
PUT {{ baseURL }}/files/3
Content-Type: application/json

{
  "title": "金典菜式",
  "link": "https://baidu.com"
}


###
# Delete files
DELETE {{ baseURL }}/files/test
Content-Type: application/json

{
  "filenames": ["Nf1E56f.webp"]
}
