# baseURL
@baseURL = http://localhost:3000

@authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjYwMDQ1ODQyLCJleHAiOjE2NjA2NTA2NDJ9.IO2NckAoiRqBqy0XkIO8TprHnqXJQ51zd3-S3SNNbQ8

###
# Find All foods
GET {{ baseURL }}/foods

###
# Find All foods
GET {{ baseURL }}/foods/search?content=肉糕

###
# Find food By Id
GET {{ baseURL }}/foods/1

###
# Create food
POST {{ baseURL }}/foods
Content-Type: application/json
Authorization: {{ authorization }}

{
  "name": "鸡汤",
	"imgUrl": "http://localhost:8080/food/xx.png",
  "desc": "汤类",
  "detail": "老少皆宜，可口美味" 
}

###
# Modify food By Id
PUT {{ baseURL }}/foods/1
Content-Type: application/json
Authorization: {{ authorization }}

{
  "desc": "蒸肉"
}

###
# Delete food By Id
DELETE {{ baseURL }}/foods/7
