# baseURL
@baseURL = http://localhost:3000

@authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwia2luZCI6InN0YWZmIiwiaWF0IjoxNjYxMDU5OTI5LCJleHAiOjE2NjE2NjQ3Mjl9.PoKoXRl6tF5Y1REFyrdvV1Wo3NXJfn1gYUhxbNPqyLA

###
# Find All foods
GET {{ baseURL }}/foods

###
# Find All foods
GET {{ baseURL }}/foods/search?content=肉糕

###
# Find food By Id
GET {{ baseURL }}/foods/1

###
# Create food
POST {{ baseURL }}/food
Content-Type: application/json
Authorization: {{ authorization }}

{
  "name": "鸡汤21",
	"imgUrl": "http://localhost:8080/food/xx.png",
  "description": "汤类",
  "detail": "老少皆宜，可口美味" 
}

###
# Modify food By Id
PUT {{ baseURL }}/foods/1
Content-Type: application/json
Authorization: {{ authorization }}

{
  "desc": "蒸肉"
}

###
# Delete food By Id
DELETE {{ baseURL }}/foods/7
