# baseURL
@baseURL = http://localhost:3000

@authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywia2luZCI6InN0YWZmIiwiaWF0IjoxNjYxMDA0MjkwLCJleHAiOjE2NjE2MDkwOTB9.RgRTiHEpCQ3KffIxDA5Xls0rfK3NcySWWrKq0mzsDWY

###
# Find All foods
GET {{ baseURL }}/foods

###
# Find All foods
GET {{ baseURL }}/foods/search?content=肉糕

###
# Find food By Id
GET {{ baseURL }}/foods/1

###
# Create food
POST {{ baseURL }}/food
Content-Type: application/json
Authorization: {{ authorization }}

{
  "name": "鸡汤5",
	"imgUrl": "http://localhost:8080/food/xx.png",
  "desc": "汤类",
  "detail": "老少皆宜，可口美味" 
}

###
# Modify food By Id
PUT {{ baseURL }}/foods/1
Content-Type: application/json
Authorization: {{ authorization }}

{
  "desc": "蒸肉"
}

###
# Delete food By Id
DELETE {{ baseURL }}/foods/7
