# baseURL
@baseURL = http://localhost:3000

###
# Find All resources
GET {{ baseURL }}/resources

###
# Find All resources
GET {{ baseURL }}/permissions

###
# Find User By Id
GET {{ baseURL }}/resource/1

###
# Create resource
POST {{ baseURL }}/resources
Content-Type: application/json

{
 "title": "修改订单",
 "permission":"order:update"
}

###
# Modify User By Id
PUT {{ baseURL }}/resources/2
Content-Type: application/json

{
	"name": "小强"
}

###
# Delete User By Id
DELETE {{ baseURL }}/resources/2
