# baseURL
@baseURL = http://localhost:3000

###
# Find All roles
GET {{ baseURL }}/roles

###
# Find User By Id
GET {{ baseURL }}/roles/1

###
# Find User By Id
GET {{ baseURL }}/roles/1/resources

###
# Create User
POST {{ baseURL }}/roles
Content-Type: application/json

{
 "name": "guest",
 "title": "客户"
}

###
# Modify User By Id
PUT {{ baseURL }}/roles/1/permissions?type=add
Content-Type: application/json

{
	"ids": [1, 4]
}

###
# Delete User By Id
DELETE {{ baseURL }}/roles/2
