# baseURL
@baseURL = http://localhost:3000

@authorization = bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjYwNjM1MDYyLCJleHAiOjE2NjEyMzk4NjJ9.dvt-07GdyeUwfHD8E39LLnTAaUONpHV0AQiN1gsRYHg

###
# Find All roles
GET {{ baseURL }}/roles

###
# Find User By Id
GET {{ baseURL }}/roles/1
Authorization: {{ authorization }}

###
# Find User By Id
GET {{ baseURL }}/roles/1/resources

###
# Create User
POST {{ baseURL }}/role
Content-Type: application/json

{
 "name": "superadmin",
 "title": "超级管理员"
}

###
# Modify User By Id
PUT {{ baseURL }}/role/1/add/permissions
Content-Type: application/json

{
	"ids": [3]
}

###
# Modify User By Id
PUT {{ baseURL }}/roles/1/remove/permissions
Content-Type: application/json

{
	"ids": [13]
}

###
# Delete User By Id
DELETE {{ baseURL }}/roles/2
