# baseURL
@baseURL = http://localhost:3000

###
# Find All foods
GET {{ baseURL }}/specs

###
# Find food By Id
GET {{ baseURL }}/specs/2

###
# Create food
POST {{ baseURL }}/specs
Content-Type: application/json

{
  "foodId": 1,
  "name": "中份",
	"price": 14
}

###
# Modify food By Id
PUT {{ baseURL }}/specs/8
Content-Type: application/json

{
  "price": 13.5
}

###
# Delete food By Id
DELETE {{ baseURL }}/specs/8
