# baseURL
@baseURL = http://localhost:3000

@authorization = bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjYwNTU2MTc5LCJleHAiOjE2NjExNjA5Nzl9.9UUOmPOB8mYdwWmnJ2nghLCVd-ojnup-8iugyUq4MEA

###
# Find All Users
GET {{ baseURL }}/users

###
# Find User By Id
GET {{ baseURL }}/users/2

###
# Create User
POST {{ baseURL }}/signup
Content-Type: application/json

{
  "phone": "+8615172435973",
	"password": "123456"
}

###
POST {{ baseURL }}/user/login
Content-Type: application/json

{
  "phone": "+8615172435973",
	"password": "123456"
}


###
# Modify User By Id
PUT {{ baseURL }}/users/2
Content-Type: application/json

{
	"name": "小强"
}

###
# Delete User By Id
DELETE {{ baseURL }}/users/2
