# baseURL
@baseURL = http://localhost:3000

###
# Find All Users
GET {{ baseURL }}/users

###
# Find User By Id
GET {{ baseURL }}/users/1

###
# Create User
POST {{ baseURL }}/signup
Content-Type: application/json

{
  "phoneNumber": "+8617207280945",
	"name": "周先生",
	"password": "123456"
}

###
# Modify User By Id
PUT {{ baseURL }}/users/2
Content-Type: application/json

{
	"name": "小强"
}

###
# Delete User By Id
DELETE {{ baseURL }}/users/2
